source {C:/Users/Roberto/Desktop/3_programmi/xilinx/data/projnav/scripts/VsimStopServer.tcl}
initIPC 1200
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -93 -explicit  PF4.vhd
vcom -93 -explicit  tbw.ant
vsim -t 1ps  -lib work tbw
run -all
quit -force
